<?php
/**
 * SpendingPartnerTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Billingo
 * @author   Billingo
 * @link     https://www.billingo.hu
 */

/**
 * Billingo API v3
 *
 * This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.
 *
 * OpenAPI spec version: 3.0.12
 * Contact: hello@billingo.hu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Billingo;

/**
 * SpendingPartnerTest Class Doc Comment
 *
 * @category    Class
 * @description SpendingPartner
 * @package     Billingo
 * @author      Billingo
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SpendingPartnerTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SpendingPartner"
     */
    public function testSpendingPartner()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "tax_code"
     */
    public function testPropertyTaxCode()
    {
    }

    /**
     * Test attribute "address"
     */
    public function testPropertyAddress()
    {
    }
}
